version: '3'

services:
  vani_next:
    image: node:18-slim
    container_name: vani_next
    working_dir: /vani_next
    ports:
      - 1300:3000
    volumes:
      - /root/next-app:/vani_next
      - /etc/localtime:/etc/localtime:ro
    command: sh ./start.sh
    restart: always
    logging:
      driver: 'json-file'
      options:
        max-file: '5'
        max-size: '25m'
